package oop;
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class DOMESTIC extends javax.swing.JFrame {
    private static final String username = "root";
    private static final String password = "$4Y my n4m3";
    private static final String dataCon = "jdbc:mysql://localhost:3306/airline_reservation";
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form DOMESTIC
     */
    public DOMESTIC() {
        initComponents();
    }
    public DOMESTIC(String msg) {
        initComponents();
     name.setText(msg);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        bag = new javax.swing.JTextField();
        seat = new javax.swing.JTextField();
        CLASSS = new javax.swing.JTextField();
        orig = new javax.swing.JComboBox<>();
        destination = new javax.swing.JComboBox<>();
        airline = new javax.swing.JComboBox<>();
        origin_choice = new javax.swing.JTextField();
        destination_choice = new javax.swing.JTextField();
        air_choice = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        CLASS111 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        BACK1 = new javax.swing.JButton();
        confirm = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 53, 364, -1));
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 81, 364, -1));
        getContentPane().add(bag, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 195, 364, -1));
        getContentPane().add(seat, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 226, 364, -1));

        CLASSS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLASSSActionPerformed(evt);
            }
        });
        getContentPane().add(CLASSS, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 257, 127, -1));

        orig.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(Choose a city)", "MNL", "CEB", "DVO", "ILO", "CRK", "PPS", "CGY", "BCD", "TAC", "ZAM", " " }));
        orig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                origActionPerformed(evt);
            }
        });
        getContentPane().add(orig, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 111, 72, -1));

        destination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(Choose a city)", "MNL", "CEB", "DVO", "ILO", "CRK", "PPS", "CGY", "BCD", "TAC", "ZAM" }));
        destination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinationActionPerformed(evt);
            }
        });
        getContentPane().add(destination, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 139, 72, -1));

        airline.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(Choose an airline)", "Air Asia Philippines", "Air Pasada", "Cebu Pacific", "Philippine Airlines" }));
        getContentPane().add(airline, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 286, 234, -1));
        getContentPane().add(origin_choice, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 111, 286, -1));
        getContentPane().add(destination_choice, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 139, 286, -1));

        air_choice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                air_choiceActionPerformed(evt);
            }
        });
        getContentPane().add(air_choice, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 286, 127, -1));

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 111, -1, -1));

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 139, 75, -1));

        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 286, -1, -1));

        CLASS111.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(Choose a class of service)", "Economy", "Business", "First-Class" }));
        getContentPane().add(CLASS111, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 257, 234, -1));

        jButton4.setText("OK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 257, -1, -1));

        jLabel11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLabel11ActionPerformed(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 166, 286, -1));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel1.setText("Please enter your flight details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 15, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Date:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 88, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Origin:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 116, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Destination:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 144, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Price for distance:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 166, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Amount of baggage in kilos/kg:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 201, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Seat number:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 229, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Class of service:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 257, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Airline of choice:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 285, -1, -1));

        BACK1.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        BACK1.setText("BACK TO HOME");
        BACK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACK1ActionPerformed(evt);
            }
        });
        jPanel1.add(BACK1, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 331, -1, 60));

        confirm.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        confirm.setText("CONFIRM");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        jPanel1.add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 331, 190, 60));

        jButton5.setText("CHECK PRICE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 166, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BACK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACK1ActionPerformed
 AIRLINE air1 = new AIRLINE();
 air1.show();
 dispose();
    }//GEN-LAST:event_BACK1ActionPerformed

    private void origActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_origActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_origActionPerformed

    private void destinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinationActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
    
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection(dataCon, username, password);
            pst = conn.prepareStatement("INSERT INTO `airline_reservation`.`domestic` (`Name`,`Date`,`Origin`,`Destination`,`Price`,`Baggage`,`Seat`,`Class`,`Airline`) VALUES(?,?,?,?,?,?,?,?,?)");
            
            pst.setString(1, name.getText());
            pst.setString(2, date.getText());
            pst.setString(3, origin_choice.getText());
            pst.setString(4, destination_choice.getText());
            pst.setString(5, jLabel11.getText());
            pst.setString(6, bag.getText());
            pst.setString(7, seat.getText());
            pst.setString(8, CLASSS.getText());
            pst.setString(9, air_choice.getText());
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Proceed to next step.", "Airline Reservation", JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    LAND_DOM landDom = new LAND_DOM();
    landDom.show();

    landDom.land_dom1.setText(name.getText());// TODO add your handling code here:
    landDom.land_dom2.setText(date.getText());
    landDom.land_dom3.setText(origin_choice.getText());
    landDom.land_dom4.setText(destination_choice.getText());
    landDom.land_dom5.setText(bag.getText());
    landDom.land_dom6.setText(seat.getText());
    landDom.land_dom7.setText(CLASSS.getText());
    landDom.land_dom8.setText(air_choice.getText());
    landDom.price.setText(jLabel11.getText());
    String one = origin_choice.getText();
    String two = destination_choice.getText();
    int thr;
    switch (one + two){
        case "MNL" + "CEB":
            thr= 2677;
            jLabel11.setText("2677");
            break;
        case "MNL" + "DVO":
             thr= 3768;
             jLabel11.setText("3768");
            break;
        case "MNL" + "ILO":
             thr= 3230;
             jLabel11.setText("3230");
            break;
        case "MNL" + "CRK":
             thr= 6454;
             jLabel11.setText("6454");
            break;
        case "MNL" + "PPS":
             thr= 3552;
             jLabel11.setText("3552");
            break;
        case "MNL" + "CGY":
             thr= 3269;
             jLabel11.setText("3269");
            break;
        case "MNL" + "BCD":
             thr= 2825;
             jLabel11.setText("2825");
            break;
        case "MNL" + "TAC":
             thr= 5415;
             jLabel11.setText("5415");
            break;
        case "MNL" + "ZAM":
             thr= 3394;
             jLabel11.setText("3394");
            break;
        case "CEB" + "MNL":
             thr= 2802;
             jLabel11.setText("2677");
            break;
        case "CEB" + "DVO":
             thr= 5349;
             jLabel11.setText("2677");
            break;
        case "CEB" + "ILO":
             thr= 2605;
             jLabel11.setText("2677");
            break;
        case "CEB" + "CRK":
             thr= 4079;
             jLabel11.setText("2677");
            break;
        case "CEB" + "PPS":
             thr= 4618;
             jLabel11.setText("2677");
            break;
        case "CEB" + "CGY":
             thr= 2675;
             jLabel11.setText("2677");
            break;
        case "CEB" + "BCD":
             thr= 2263;
             jLabel11.setText("2677");
            break;
        case "CEB" + "TAC":
             thr= 4645;
             jLabel11.setText("2677");
            break;
        case "CEB" + "ZAM":
             thr= 2883;
             jLabel11.setText("2677");
            break;
        case "DVO" + "MNL":
             thr= 4479;
             jLabel11.setText("2677");
            break;
        case "DVO" + "CEB":
             thr= 4605;
             jLabel11.setText("2677");
            break;
        case "DVO" + "ILO":
             thr= 4619;
             jLabel11.setText("2677");
            break;
        case "DVO" + "CRK":
             thr= 9850;
             jLabel11.setText("2677");
            break;
        case "DVO" + "PPS":
             thr= 7317;
             jLabel11.setText("2677");
            break;
        case "DVO" + "CGY":
             thr= 7594;
             jLabel11.setText("2677");
            break;
        case "DVO" + "BCD":
             thr= 4775;
             jLabel11.setText("2677");
            break;
        case "DVO" + "TAC":
             thr= 8852;
             jLabel11.setText("2677");
            break;
        case "DVO" + "ZAM":
             thr= 8745;
             jLabel11.setText("2677");
            break;
        case "ILO" + "MNL":
             thr= 2685;
             jLabel11.setText("2677");
            break;
        case "ILO" + "CEB":
             thr= 2513;
             jLabel11.setText("2677");
            break;
        case "ILO" + "DVO":
             thr= 5612;
             jLabel11.setText("2677");
            break;
        case "ILO" + "CRK":
             thr= 7564;
             jLabel11.setText("2677");
            break;
        case "ILO" + "PPS":
             thr= 6651;
             jLabel11.setText("2677");
            break;
        case "ILO" + "CGY":
             thr= 4595;
             jLabel11.setText("2677");
            break;
        case "ILO" + "BCD":
             thr= 8841;
             jLabel11.setText("2677");
            break;
        case "ILO" + "TAC":
             thr= 7052;
             jLabel11.setText("2677");
            break;
        case "ILO" + "ZAM":
             thr= 7154;
             jLabel11.setText("2677");
            break;
        case "CRK" + "MNL":
             thr= 5914;
             jLabel11.setText("2677");
            break;
        case "CRK" + "CEB":
             thr= 2895;
             jLabel11.setText("2677");
            break;
        case "CRK" + "DVO":
             thr= 7494;
             jLabel11.setText("2677");
            break;
        case "CRK" + "ILO":
             thr= 7344;
             jLabel11.setText("2677");
            break;
        case "CRK" + "PPS":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "CRK" + "CGY":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "CRK" + "BCD":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "CRK" + "TAC":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "CRK" + "ZAM":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "PPS" + "MNL":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "PPS" + "CEB":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "PPS" + "DVO":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "PPS" + "ILO":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "PPS" + "CRK":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "PPS" + "CGY":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "PPS" + "BCD":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "PPS" + "TAC":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "PPS" + "ZAM":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "CGY" + "MNL":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "CGY" + "CEB":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "CGY" + "DVO":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "CGY" + "ILO":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "CGY" + "CRK":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "CGY" + "PPS":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "CGY" + "BCD":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "CGY" + "TAC":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "CGY" + "ZAM":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "BCD" + "MNL":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "BCD" + "CEB":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "BCD" + "DVO":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "BCD" + "ILO":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "BCD" + "CRK":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "BCD" + "PPS":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "BCD" + "CGY":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "BCD" + "TAC":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "BCD" + "ZAM":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "TAC" + "MNL":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "TAC" + "CEB":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "TAC" + "DVO":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "TAC" + "ILO":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "TAC" + "CRK":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "TAC" + "PPS":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "TAC" + "CGY":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "TAC" + "BCD":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "TAC" + "ZAM":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "ZAM" + "MNL":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "ZAM" + "CEB":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "ZAM" + "DVO":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "ZAM" + "ILO":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "ZAM" + "CRK":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "ZAM" + "PPS":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "ZAM" + "CGY":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "ZAM" + "BCD":
             thr= 4228;
             jLabel11.setText("2677");
            break;
        case "ZAM" + "ZAM":
             thr= 4228;
             jLabel11.setText("2677");
            break;
    }
dispose();
// TODO add your handling code here:


    }//GEN-LAST:event_confirmActionPerformed

    private void air_choiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_air_choiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_air_choiceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 origin_choice.setText(orig.getSelectedItem().toString());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 destination_choice.setText(destination.getSelectedItem().toString());       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
air_choice.setText(airline.getSelectedItem().toString());        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void CLASSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLASSSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CLASSSActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
CLASSS.setText(CLASS111.getSelectedItem().toString());        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLabel11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
String one = origin_choice.getText();
String two = destination_choice.getText();
int thr;
switch (one + two){
    case "MNL" + "CEB":
        thr= 2677;
        jLabel11.setText("2677");
        break;
    case "MNL" + "DVO":
         thr= 3768;
         jLabel11.setText("3768");
        break;
    case "MNL" + "ILO":
         thr= 3230;
         jLabel11.setText("3230");
        break;
    case "MNL" + "CRK":
         thr= 6454;
         jLabel11.setText("6454");
        break;
    case "MNL" + "PPS":
         thr= 3552;
         jLabel11.setText("3552");
        break;
    case "MNL" + "CGY":
         thr= 3269;
         jLabel11.setText("3269");
        break;
    case "MNL" + "BCD":
         thr= 2825;
         jLabel11.setText("2825");
        break;
    case "MNL" + "TAC":
         thr= 5415;
         jLabel11.setText("5415");
        break;
    case "MNL" + "ZAM":
         thr= 3394;
         jLabel11.setText("3394");
        break;
    case "CEB" + "MNL":
         thr= 2802;
         jLabel11.setText("2677");
        break;
    case "CEB" + "DVO":
         thr= 5349;
         jLabel11.setText("2677");
        break;
    case "CEB" + "ILO":
         thr= 2605;
         jLabel11.setText("2677");
        break;
    case "CEB" + "CRK":
         thr= 4079;
         jLabel11.setText("2677");
        break;
    case "CEB" + "PPS":
         thr= 4618;
         jLabel11.setText("2677");
        break;
    case "CEB" + "CGY":
         thr= 2675;
         jLabel11.setText("2677");
        break;
    case "CEB" + "BCD":
         thr= 2263;
         jLabel11.setText("2677");
        break;
    case "CEB" + "TAC":
         thr= 4645;
         jLabel11.setText("2677");
        break;
    case "CEB" + "ZAM":
         thr= 2883;
         jLabel11.setText("2677");
        break;
    case "DVO" + "MNL":
         thr= 4479;
         jLabel11.setText("2677");
        break;
    case "DVO" + "CEB":
         thr= 4605;
         jLabel11.setText("2677");
        break;
    case "DVO" + "ILO":
         thr= 4619;
         jLabel11.setText("2677");
        break;
    case "DVO" + "CRK":
         thr= 9850;
         jLabel11.setText("2677");
        break;
    case "DVO" + "PPS":
         thr= 7317;
         jLabel11.setText("2677");
        break;
    case "DVO" + "CGY":
         thr= 7594;
         jLabel11.setText("2677");
        break;
    case "DVO" + "BCD":
         thr= 4775;
         jLabel11.setText("2677");
        break;
    case "DVO" + "TAC":
         thr= 8852;
         jLabel11.setText("2677");
        break;
    case "DVO" + "ZAM":
         thr= 8745;
         jLabel11.setText("2677");
        break;
    case "ILO" + "MNL":
         thr= 2685;
         jLabel11.setText("2677");
        break;
    case "ILO" + "CEB":
         thr= 2513;
         jLabel11.setText("2677");
        break;
    case "ILO" + "DVO":
         thr= 5612;
         jLabel11.setText("2677");
        break;
    case "ILO" + "CRK":
         thr= 7564;
         jLabel11.setText("2677");
        break;
    case "ILO" + "PPS":
         thr= 6651;
         jLabel11.setText("2677");
        break;
    case "ILO" + "CGY":
         thr= 4595;
         jLabel11.setText("2677");
        break;
    case "ILO" + "BCD":
         thr= 8841;
         jLabel11.setText("2677");
        break;
    case "ILO" + "TAC":
         thr= 7052;
         jLabel11.setText("2677");
        break;
    case "ILO" + "ZAM":
         thr= 7154;
         jLabel11.setText("2677");
        break;
    case "CRK" + "MNL":
         thr= 5914;
         jLabel11.setText("2677");
        break;
    case "CRK" + "CEB":
         thr= 2895;
         jLabel11.setText("2677");
        break;
    case "CRK" + "DVO":
         thr= 7494;
         jLabel11.setText("2677");
        break;
    case "CRK" + "ILO":
         thr= 7344;
         jLabel11.setText("2677");
        break;
    case "CRK" + "PPS":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "CRK" + "CGY":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "CRK" + "BCD":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "CRK" + "TAC":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "CRK" + "ZAM":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "PPS" + "MNL":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "PPS" + "CEB":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "PPS" + "DVO":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "PPS" + "ILO":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "PPS" + "CRK":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "PPS" + "CGY":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "PPS" + "BCD":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "PPS" + "TAC":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "PPS" + "ZAM":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "CGY" + "MNL":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "CGY" + "CEB":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "CGY" + "DVO":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "CGY" + "ILO":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "CGY" + "CRK":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "CGY" + "PPS":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "CGY" + "BCD":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "CGY" + "TAC":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "CGY" + "ZAM":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "BCD" + "MNL":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "BCD" + "CEB":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "BCD" + "DVO":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "BCD" + "ILO":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "BCD" + "CRK":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "BCD" + "PPS":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "BCD" + "CGY":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "BCD" + "TAC":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "BCD" + "ZAM":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "TAC" + "MNL":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "TAC" + "CEB":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "TAC" + "DVO":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "TAC" + "ILO":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "TAC" + "CRK":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "TAC" + "PPS":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "TAC" + "CGY":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "TAC" + "BCD":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "TAC" + "ZAM":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "ZAM" + "MNL":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "ZAM" + "CEB":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "ZAM" + "DVO":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "ZAM" + "ILO":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "ZAM" + "CRK":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "ZAM" + "PPS":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "ZAM" + "CGY":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "ZAM" + "BCD":
         thr= 4228;
         jLabel11.setText("2677");
        break;
    case "ZAM" + "ZAM":
         thr= 4228;
         jLabel11.setText("2677");
        break;        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DOMESTIC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DOMESTIC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DOMESTIC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DOMESTIC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DOMESTIC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACK1;
    private javax.swing.JComboBox<String> CLASS111;
    private javax.swing.JTextField CLASSS;
    private javax.swing.JTextField air_choice;
    private javax.swing.JComboBox<String> airline;
    private javax.swing.JTextField bag;
    private javax.swing.JButton confirm;
    private javax.swing.JTextField date;
    private javax.swing.JComboBox<String> destination;
    private javax.swing.JTextField destination_choice;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JTextField jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    public javax.swing.JComboBox<String> orig;
    private javax.swing.JTextField origin_choice;
    private javax.swing.JTextField seat;
    // End of variables declaration//GEN-END:variables
}
