package oop;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class INTERNATIONAL extends javax.swing.JFrame {
    private static final String username = "root";
    private static final String password = "$4Y my n4m3";
    private static final String dataCon = "jdbc:mysql://localhost:3306/airline_reservation";
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form INTERNATIONAL
     */
    public INTERNATIONAL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name1 = new javax.swing.JTextField();
        date1 = new javax.swing.JTextField();
        bag1 = new javax.swing.JTextField();
        seat1 = new javax.swing.JTextField();
        CLASS = new javax.swing.JTextField();
        airline1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        orig1 = new javax.swing.JComboBox<>();
        destination = new javax.swing.JComboBox<>();
        airline11 = new javax.swing.JComboBox<>();
        CLASS1 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        origin1 = new javax.swing.JTextField();
        destination1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlab1 = new javax.swing.JLabel();
        jlab2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        BACK2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 58, 350, -1));
        getContentPane().add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 86, 350, -1));
        getContentPane().add(bag1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 212, 350, -1));
        getContentPane().add(seat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 350, -1));
        getContentPane().add(CLASS, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 268, 210, -1));
        getContentPane().add(airline1, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 297, 210, -1));

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 297, 52, -1));

        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 146, 51, -1));

        jButton4.setText("OK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 117, 51, -1));

        orig1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(Choose a country)", "Brunei", "Burma", "Cambodia", "Indonesia", "Laos", "Malaysia", "Philippines", "Singapore", "Thailand", "Vietnam" }));
        orig1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orig1ActionPerformed(evt);
            }
        });
        getContentPane().add(orig1, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 117, 132, -1));

        destination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(Choose a country)", "Brunei", "Burma", "Cambodia", "Indonesia", "Laos", "Malaysia", "Philippines", "Singapore", "Thailand", "Vietnam." }));
        getContentPane().add(destination, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 146, 132, -1));

        airline11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(Choose an airline)", "Air Asia Phillipines", "Air Pasada", "Cebu pacific", "Philippine Airlines" }));
        getContentPane().add(airline11, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 297, -1, -1));

        CLASS1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(Choose a class of service)", "Economy", "Business", "First-Class" }));
        getContentPane().add(CLASS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 268, 133, -1));

        jButton5.setText("OK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 268, 52, -1));
        getContentPane().add(origin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 117, 210, -1));
        getContentPane().add(destination1, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 146, 210, -1));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 36)); // NOI18N
        jLabel1.setText("Please enter your flight details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jlab1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlab1.setText("Name:");
        jPanel1.add(jlab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        jlab2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlab2.setText("Date:");
        jPanel1.add(jlab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Origin:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Destination:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Price:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Amount of baggage in kilos/kg:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Seat no:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, -1, 10));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Class of service:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Airline of choice:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        BACK2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BACK2.setText("BACK TO HOME");
        BACK2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACK2ActionPerformed(evt);
            }
        });
        jPanel1.add(BACK2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 240, 50));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("CONFIRM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 190, 50));

        jButton6.setText("CHECK PRICE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 210, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BACK2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACK2ActionPerformed
        AIRLINE air1 = new AIRLINE();
        air1.show();
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_BACK2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection(dataCon, username, password);
            pst = conn.prepareStatement("INSERT INTO `airline_reservation`.`international` (`Name`,`Date`,`Origin`,`Destination`,`Price`,`Baggage`,`Seat`,`Class`,`Airline`) VALUES(?,?,?,?,?,?,?,?,?)");
            
            pst.setString(1, name1.getText());
            pst.setString(2, date1.getText());
            pst.setString(3, origin1.getText());
            pst.setString(4, destination1.getText());
            pst.setString(5, jTextField1.getText());
            pst.setString(6, bag1.getText());
            pst.setString(7, seat1.getText());
            pst.setString(8, CLASS.getText());
            pst.setString(9, airline1.getText());
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Proceed to next step.", "Airline Reservation", JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        LAND_INTER landInter = new LAND_INTER(); 
        landInter.show();
        landInter.land_int1.setText(name1.getText());
        landInter.land_int2.setText(date1.getText());
        landInter.land_int3.setText(origin1.getText());
        landInter.land_int4.setText(destination1.getText());
        landInter.land_int5.setText(bag1.getText());
        landInter.land_int6.setText(seat1.getText());
        landInter.land_int7.setText(CLASS.getText());
        landInter.land_int8.setText(airline1.getText());
        landInter.price.setText(jTextField1.getText());
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
origin1.setText(orig1.getSelectedItem().toString());        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
destination1.setText(destination.getSelectedItem().toString());        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
airline1.setText(airline11.getSelectedItem().toString());        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
CLASS.setText(CLASS1.getSelectedItem().toString());    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
String one = origin1.getText();
String two = destination1.getText();
int thr;
switch (one + two){
    case "Brunei" + "Burma":
        thr= 2677;
        jTextField1.setText("2677");
        break;
    case "Brunei" + "Cambodia":
        thr= 2677;
        jTextField1.setText("2677");
        break;
    case "Brunei" + "Indonesia":
        thr= 2677;
        jTextField1.setText("2677");
        break;
    case "Brunei" + "Laos":
        thr= 2677;
        jTextField1.setText("2677");
        break;
     case "Brunei" + "Malaysia":
        thr= 2677;
        jTextField1.setText("2677");
        break;
        case "Brunei" + "Philippines":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Brunei" + "Singapore":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Brunei" + "Thailand":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Brunei" + "Vietnam":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Burma" + "Brunei":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Burma" + "Cambodia":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Burma" + "Indonesia":
        thr= 2677;
        jTextField1.setText("2677");
        break;
    case "Burma" + "Laos":
        thr= 2677;
        jTextField1.setText("2677");
        break;
     case "Burma" + "Malaysia":
        thr= 2677;
        jTextField1.setText("2677");
        break;
        case "Burma" + "Philippines":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Burma" + "Singapore":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Burma" + "Thailand":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Burma" + "Vietnam":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Cambodia" + "Brunei":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Cambodia" + "Burma":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Cambodia" + "Indonesia":
        thr= 2677;
        jTextField1.setText("2677");
        break;
    case "Cambodia" + "Laos":
        thr= 2677;
        jTextField1.setText("2677");
        break;
     case "Cambodia" + "Malaysia":
        thr= 2677;
        jTextField1.setText("2677");
        break;
        case "Cambodia" + "Philippines":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Cambodia" + "Singapore":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Cambodia" + "Thailand":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Cambodia" + "Vietnam":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Indonesia" + "Brunei":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Indonesia" + "Burma":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Indonesia" + "Cambodia":
        thr= 2677;
        jTextField1.setText("2677");
        break;
    case "Indonesia" + "Laos":
        thr= 2677;
        jTextField1.setText("2677");
        break;
     case "Indonesia" + "Malaysia":
        thr= 2677;
        jTextField1.setText("2677");
        break;
        case "Indonesia" + "Philippines":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Indonesia" + "Singapore":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Indonesia" + "Thailand":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Indonesia" + "Vietnam":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Laos" + "Brunei":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Laos" + "Burma":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Laos" + "Cambodia":
        thr= 2677;
        jTextField1.setText("2677");
        break;
    case "Laos" + "Indonesia":
        thr= 2677;
        jTextField1.setText("2677");
        break;
     case "Laos" + "Malaysia":
        thr= 2677;
        jTextField1.setText("2677");
        break;
        case "Laos" + "Philippines":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Laos" + "Singapore":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Laos" + "Thailand":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Laos" + "Vietnam":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Malaysia" + "Brunei":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Malaysia" + "Burma":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Malaysia" + "Cambodia":
        thr= 2677;
        jTextField1.setText("2677");
        break;
    case "Malaysia" + "Indonesia":
        thr= 2677;
        jTextField1.setText("2677");
        break;
     case "Malaysia" + "Laos":
        thr= 2677;
        jTextField1.setText("2677");
        break;
        case "Malaysia" + "Philippines":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Malaysia" + "Singapore":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Malaysia" + "Thailand":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Malaysia" + "Vietnam":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Philippines" + "Brunei":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Philippines" + "Burma":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Philippines" + "Cambodia":
        thr= 2677;
        jTextField1.setText("2677");
        break;
    case "Philippines" + "Indonesia":
        thr= 2677;
        jTextField1.setText("2677");
        break;
     case "Philippines" + "Laos":
        thr= 2677;
        jTextField1.setText("2677");
        break;
        case "Philippines" + "Malaysia":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Philippines" + "Singapore":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Philippines" + "Thailand":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Philippines" + "Vietnam":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Singapore" + "Brunei":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Singapore" + "Burma":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Singapore" + "Cambodia":
        thr= 2677;
        jTextField1.setText("2677");
        break;
    case "Singapore" + "Indonesia":
        thr= 2677;
        jTextField1.setText("2677");
        break;
     case "Singapore" + "Laos":
        thr= 2677;
        jTextField1.setText("2677");
        break;
        case "Singapore" + "Malaysia":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Singapore" + "Philippines":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Singapore" + "Thailand":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Singapore" + "Vietnam":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Thailand" + "Brunei":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Thailand" + "Burma":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Thailand" + "Cambodia":
        thr= 2677;
        jTextField1.setText("2677");
        break;
    case "Thailand" + "Indonesia":
        thr= 2677;
        jTextField1.setText("2677");
        break;
     case "Thailand" + "Laos":
        thr= 2677;
        jTextField1.setText("2677");
        break;
        case "Thailand" + "Malaysia":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Thailand" + "Philippines":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Thailand" + "Singapore":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Thailand" + "Vietnam":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Vietnam" + "Brunei":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Vietnam" + "Burma":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Vietnam" + "Cambodia":
        thr= 2677;
        jTextField1.setText("2677");
        break;
    case "Vietnam" + "Indonesia":
        thr= 2677;
        jTextField1.setText("2677");
        break;
     case "Vietnam" + "Laos":
        thr= 2677;
        jTextField1.setText("2677");
        break;
        case "Vietnam" + "Malaysia":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Vietnam" + "Philippines":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Vietnam" + "Singapore":
        thr= 2677;
        jTextField1.setText("2677");
        break;
case "Vietnam" + "Thailand":
        thr= 2677;
        jTextField1.setText("2677");
        break;// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed
    }
    private void orig1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orig1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orig1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INTERNATIONAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INTERNATIONAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INTERNATIONAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INTERNATIONAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new INTERNATIONAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACK2;
    private javax.swing.JTextField CLASS;
    private javax.swing.JComboBox<String> CLASS1;
    private javax.swing.JTextField airline1;
    private javax.swing.JComboBox<String> airline11;
    private javax.swing.JTextField bag1;
    private javax.swing.JTextField date1;
    private javax.swing.JComboBox<String> destination;
    public javax.swing.JTextField destination1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jlab1;
    private javax.swing.JLabel jlab2;
    private javax.swing.JTextField name1;
    private javax.swing.JComboBox<String> orig1;
    public javax.swing.JTextField origin1;
    private javax.swing.JTextField seat1;
    // End of variables declaration//GEN-END:variables
}
