package oop;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class LAND_DOM extends javax.swing.JFrame {

    /**
     * Creates new form LAND_DOM
     */
    public LAND_DOM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        land_dom1 = new javax.swing.JLabel();
        land_dom2 = new javax.swing.JLabel();
        land_dom3 = new javax.swing.JLabel();
        land_dom4 = new javax.swing.JLabel();
        land_dom5 = new javax.swing.JLabel();
        land_dom6 = new javax.swing.JLabel();
        land_dom7 = new javax.swing.JLabel();
        land_dom8 = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("BACK TO DOMESTIC flight page");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        land_dom1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        land_dom1.setText("jLabel2");

        land_dom2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        land_dom2.setText("jLabel3");

        land_dom3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        land_dom3.setText("jLabel4");

        land_dom4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        land_dom4.setText("jLabel5");

        land_dom5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        land_dom5.setText("jLabel6");

        land_dom6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        land_dom6.setText("jLabel7");

        land_dom7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        land_dom7.setText("jLabel8");

        land_dom8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        land_dom8.setText("jLabel2");

        price.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        price.setText("PRICE");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("DOMESTIC Flight details");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(land_dom2)
                            .addComponent(land_dom3)
                            .addComponent(land_dom4)
                            .addComponent(land_dom5)
                            .addComponent(land_dom6)
                            .addComponent(land_dom7)
                            .addComponent(land_dom8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(land_dom1)
                                .addGap(125, 125, 125)
                                .addComponent(price)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(land_dom1)
                    .addComponent(price))
                .addGap(2, 2, 2)
                .addComponent(land_dom2)
                .addGap(2, 2, 2)
                .addComponent(land_dom3)
                .addGap(2, 2, 2)
                .addComponent(land_dom4)
                .addGap(2, 2, 2)
                .addComponent(land_dom5)
                .addGap(2, 2, 2)
                .addComponent(land_dom6)
                .addGap(2, 2, 2)
                .addComponent(land_dom7)
                .addGap(2, 2, 2)
                .addComponent(land_dom8)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
DOMESTIC dome = new DOMESTIC();
dome.show();
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        PAYMENT_DOM payDom = new PAYMENT_DOM();

payDom.show();
payDom.name1.setText(land_dom1.getText());
payDom.airChoice.setText(land_dom8.getText());
payDom.orig1.setText(land_dom3.getText());
payDom.dest1.setText(land_dom4.getText());
payDom.bag1.setText(land_dom5.getText());
payDom.jLabel11.setText(price.getText());
int flight = 5;
switch (flight){
    case 1:
        System.out.println("1500");
        break;
        case 2:
        System.out.println("1750");
        break;
        case 3:
        System.out.println("2000");
        break;
        case 4:
        System.out.println("2250");
        break;
            
}  

dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LAND_DOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LAND_DOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LAND_DOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LAND_DOM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LAND_DOM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel land_dom1;
    public javax.swing.JLabel land_dom2;
    public javax.swing.JLabel land_dom3;
    public javax.swing.JLabel land_dom4;
    public javax.swing.JLabel land_dom5;
    public javax.swing.JLabel land_dom6;
    public javax.swing.JLabel land_dom7;
    public javax.swing.JLabel land_dom8;
    public javax.swing.JLabel price;
    // End of variables declaration//GEN-END:variables
}
