package oop;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class LAND_INTER extends javax.swing.JFrame {

    /**
     * Creates new form LAND_INTER
     */
    public LAND_INTER() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        land_int1 = new javax.swing.JLabel();
        land_int2 = new javax.swing.JLabel();
        land_int3 = new javax.swing.JLabel();
        land_int4 = new javax.swing.JLabel();
        land_int5 = new javax.swing.JLabel();
        land_int6 = new javax.swing.JLabel();
        land_int7 = new javax.swing.JLabel();
        land_int8 = new javax.swing.JLabel();
        price = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("INTERNATIONAL flight page");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("BACK TO INTERNATIONAL flight page");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        land_int1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        land_int1.setText("jLabel2");

        land_int2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        land_int2.setText("jLabel3");

        land_int3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        land_int3.setText("jLabel4");

        land_int4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        land_int4.setText("jLabel5");

        land_int5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        land_int5.setText("jLabel6");

        land_int6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        land_int6.setText("jLabel7");

        land_int7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        land_int7.setText("jLabel8");

        land_int8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        land_int8.setText("jLabel9");

        price.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        price.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(land_int1)
                                .addGap(174, 174, 174)
                                .addComponent(price))
                            .addComponent(land_int2)
                            .addComponent(land_int3)
                            .addComponent(land_int4)
                            .addComponent(land_int5)
                            .addComponent(land_int6)
                            .addComponent(land_int7)
                            .addComponent(land_int8))
                        .addGap(181, 181, 181))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(83, 83, 83))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(land_int1)
                    .addComponent(price))
                .addGap(6, 6, 6)
                .addComponent(land_int2)
                .addGap(6, 6, 6)
                .addComponent(land_int3)
                .addGap(6, 6, 6)
                .addComponent(land_int4)
                .addGap(6, 6, 6)
                .addComponent(land_int5)
                .addGap(6, 6, 6)
                .addComponent(land_int6)
                .addGap(6, 6, 6)
                .addComponent(land_int7)
                .addGap(6, 6, 6)
                .addComponent(land_int8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                .addGap(75, 75, 75))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 INTERNATIONAL inter = new INTERNATIONAL();
 inter.show();
 dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
PAYMENT_INT payInt = new PAYMENT_INT();
payInt.show();
payInt.jLabel6.setText(land_int8.getText());
payInt.jLabel7.setText(land_int3.getText());
payInt.jLabel8.setText(land_int4.getText());
payInt.jLabel9.setText(land_int5.getText());
payInt.jLabel1.setText(land_int1.getText());
payInt.PRICE.setText(price.getText());

dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LAND_INTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LAND_INTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LAND_INTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LAND_INTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LAND_INTER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel land_int1;
    public javax.swing.JLabel land_int2;
    public javax.swing.JLabel land_int3;
    public javax.swing.JLabel land_int4;
    public javax.swing.JLabel land_int5;
    public javax.swing.JLabel land_int6;
    public javax.swing.JLabel land_int7;
    public javax.swing.JLabel land_int8;
    public javax.swing.JLabel price;
    // End of variables declaration//GEN-END:variables
}
